// desktop/src/lib/components/MessageBubble.svelte
<script lang="ts">
	import Markdown from './Markdown.svelte';
	import type { ChatMessage, MessageContent } from '$lib/sessions';

	let { message, streaming = false }: { message: ChatMessage; streaming?: boolean } = $props();

	let isUser = $derived(message.role === 'user');
	let isMultipart = $derived(Array.isArray(message.content));

	let textContent = $derived(
		typeof message.content === 'string'
			? message.content
			: (message.content as MessageContent[])
					.filter((p) => p.type === 'text')
					.map((p) => p.text)
					.join('\n')
	);

	let imageUrls = $derived(
		Array.isArray(message.content)
			? (message.content as MessageContent[])
					.filter((p) => p.type === 'image_url' && p.image_url?.url)
					.map((p) => p.image_url!.url)
			: []
	);
</script>

<div class="bubble-row" class:user={isUser}>
	<div class="bubble" class:user-bubble={isUser} class:assistant-bubble={!isUser}>
		{#if isUser}
			{#if imageUrls.length > 0}
				<div class="attached-images">
					{#each imageUrls as url}
						<img src={url} alt="附件图片" class="attached-img" loading="lazy" />
					{/each}
				</div>
			{/if}
			<p class="user-text">{textContent}</p>
		{:else}
			<Markdown content={typeof message.content === 'string' ? message.content : textContent} />
			{#if streaming}
				<span class="cursor">▋</span>
			{/if}
		{/if}
	</div>
</div>

<style>
	.bubble-row {
		display: flex;
		padding: var(--space-2) var(--space-10);
	}

	.bubble-row.user {
		justify-content: flex-end;
	}

	.bubble {
		max-width: 75%;
		padding: var(--space-5) var(--space-8);
		border-radius: var(--radius-lg);
	}

	.user-bubble {
		background: var(--bg-user-bubble);
		border-bottom-right-radius: var(--radius-sm);
	}

	.assistant-bubble {
		background: var(--bg-assistant-bubble);
		border-bottom-left-radius: var(--radius-sm);
	}

	.user-text {
		white-space: pre-wrap;
		word-break: break-word;
	}

	.attached-images {
		display: flex;
		flex-wrap: wrap;
		gap: var(--space-3);
		margin-bottom: var(--space-4);
	}

	.attached-img {
		max-width: 200px;
		max-height: 200px;
		border-radius: var(--radius);
		object-fit: cover;
	}

	.cursor {
		display: inline-block;
		animation: blink 1s step-end infinite;
		color: var(--accent);
	}

	@keyframes blink {
		50% {
			opacity: 0;
		}
	}
</style>

// desktop/src/react/components/MessageBubble.tsx
import { Suspense, lazy } from "react";
import type { ChatMessage, MessageContent } from "../types";

const Markdown = lazy(() => import("./Markdown"));

function extractText(content: string | MessageContent[]) {
  if (typeof content === "string") return content;
  return content
    .filter((part) => part.type === "text")
    .map((part) => part.text || "")
    .join("\n");
}

function extractImages(content: string | MessageContent[]) {
  if (typeof content === "string") return [];
  return content
    .filter((part) => part.type === "image_url" && part.image_url?.url)
    .map((part) => part.image_url!.url);
}

export default function MessageBubble({
  message,
  streaming = false,
  workspacePath,
}: {
  message: ChatMessage;
  streaming?: boolean;
  workspacePath?: string;
}) {
  const isUser = message.role === "user";
  const text = extractText(message.content);
  const images = extractImages(message.content);

  return (
    <div className={`bubble-row ${isUser ? "user" : "assistant"}`}>
      <div className={`bubble ${isUser ? "user-bubble" : "assistant-bubble"}`}>
        {isUser ? (
          <>
            {images.length > 0 && (
              <div className="attached-images">
                {images.map((url) => (
                  <img key={url} src={url} alt="附件图片" className="attached-img" loading="lazy" />
                ))}
              </div>
            )}
            <p className="user-text">{text}</p>
          </>
        ) : (
          <>
            <Suspense fallback={<pre className="assistant-plain-text">{text}</pre>}>
              <Markdown content={text} workspacePath={workspacePath} />
            </Suspense>
            {streaming && <span className="cursor">▋</span>}
          </>
        )}
      </div>
    </div>
  );
}
